# Generated by Django 6.0.4 on 2026-04-22 18:23

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobembedding',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.AddField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='posted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='work_setup',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobembedding',
            name='model_name',
            field=models.CharField(default='nomic-embed-text', max_length=100),
        ),
        migrations.AddField(
            model_name='jobembedding',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobembedding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobembedding',
            table=None,
        ),
    ]
