# Generated by Django 6.0.4 on 2026-04-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_alter_jobembedding_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
        migrations.AlterModelTable(
            name='jobembedding',
            table='job_embeddings',
        ),
    ]
