# Generated by Django 6.0.4 on 2026-04-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_table_alter_jobembedding_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, db_column='company_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, db_column='type', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_setup',
            field=models.CharField(blank=True, db_column='setup', max_length=100),
        ),
    ]
