# Generated by Django 6.0.4 on 2026-04-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_employer_id_alter_job_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
