# Generated by Django 6.0.4 on 2026-04-22 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name', 'email']},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to='resumes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='needs_ocr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='availability',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_setup',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('ocr_needed', 'OCR Needed'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='resume',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
