# Generated by Django 6.0.4 on 2026-04-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_resume_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resume',
            table='students_resume',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students_student',
        ),
    ]
