# Generated by Django 6.0.4 on 2026-04-22 18:23

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pipeline', '0001_initial'),
        ('jobs', '0002_alter_job_options_alter_jobembedding_options_and_more'),
        ('students', '0002_alter_resume_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ['-match_percentage', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='parsedprofile',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentembedding',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='rationale_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='students.resume'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='similarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='parser_model',
            field=models.CharField(default='qwen3:4b', max_length=100),
        ),
        migrations.AddField(
            model_name='studentembedding',
            name='model_name',
            field=models.CharField(default='nomic-embed-text', max_length=100),
        ),
        migrations.AddField(
            model_name='studentembedding',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentembedding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parsedprofile',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='parsedprofile',
            name='job_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='parsedprofile',
            name='raw_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='parsedprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=768),
        ),
        migrations.AddConstraint(
            model_name='matchresult',
            constraint=models.UniqueConstraint(fields=('resume', 'job'), name='unique_resume_job_match'),
        ),
        migrations.AlterModelTable(
            name='matchresult',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parsedprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentembedding',
            table=None,
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='match_score',
        ),
    ]
