# Generated by Django 6.0.4 on 2026-04-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_pipeline', '0002_alter_matchresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchresult',
            table='match_results',
        ),
        migrations.AlterModelTable(
            name='parsedprofile',
            table='parsed_profiles',
        ),
        migrations.AlterModelTable(
            name='studentembedding',
            table='student_embeddings',
        ),
    ]
